INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '0102030405', 'Juan Pérez', 'juan.perez@example.com', '0991234567');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '0605040302', 'Ana Gómez', 'ana.gomez@example.com', '0997654321');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('PASAPORTE', 'AB1234567', 'Carlos Mendoza', 'carlos.mendoza@example.com', '0981112233');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '1109876543', 'Lucía Salazar', 'lucia.salazar@example.com', '0987654321');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('RUC', '1790012345001', 'Pedro Cedeño', 'pedro.cedeno@example.com', '0971122334');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '1802345678', 'María Torres', 'maria.torres@example.com', '0968877665');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('PASAPORTE', 'CD9876543', 'Roberto Vega', 'roberto.vega@example.com', '0959988776');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '0911223344', 'Daniela Ruiz', 'daniela.ruiz@example.com', '0945566778');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('RUC', '0999999999001', 'Empresa Ejemplo', 'contacto@empresa.com', '0933344556');
INSERT INTO client (identification_type, identification_number, full_name, email, cellphone) VALUES ('CEDULA', '1718123456', 'Sofía López', 'sofia.lopez@example.com', '0922233445');
INSERT INTO address (province, city, address, client_id) VALUES ('Pichincha', 'Quito', 'Av. Amazonas N34-120', 1);
INSERT INTO address (province, city, address, client_id) VALUES ('Guayas', 'Guayaquil', 'Diez de agosto', 2);
INSERT INTO address (province, city, address, client_id) VALUES ('Guayas', 'Guayaquil', 'Calle Los Ríos 230', 1);
INSERT INTO address (province, city, address, client_id) VALUES ('Azuay', 'Cuenca', 'Av. Solano 123', 2);
INSERT INTO address (province, city, address, client_id) VALUES ('Manabí', 'Portoviejo', 'Av. Universitaria 456', 3);
INSERT INTO address (province, city, address, client_id) VALUES ('Tungurahua', 'Ambato', 'Calle Bolívar 789', 4);
INSERT INTO address (province, city, address, client_id) VALUES ('Loja', 'Loja', 'Av. Emiliano Ortega 111', 4);
INSERT INTO address (province, city, address, client_id) VALUES ('Esmeraldas', 'Esmeraldas', 'Av. Libertad 202', 3);
INSERT INTO address (province, city, address, client_id) VALUES ('El Oro', 'Machala', 'Calle Rocafuerte 305', 5);
INSERT INTO address (province, city, address, client_id) VALUES ('Chimborazo', 'Riobamba', 'Av. Daniel León Borja 406', 6);
INSERT INTO address (province, city, address, client_id) VALUES ('Imbabura', 'Ibarra', 'Calle Sucre 507', 5);
INSERT INTO address (province, city, address, client_id) VALUES ('Santa Elena', 'La Libertad', 'Av. Malecón 110', 6);
INSERT INTO address (province, city, address, client_id) VALUES ('Pastaza', 'Puyo', 'Calle 9 de Octubre 215', 7);
INSERT INTO address (province, city, address, client_id) VALUES ('Carchi', 'Tulcán', 'Av. Bolívar 310', 7);
INSERT INTO address (province, city, address, client_id) VALUES ('Sucumbíos', 'Nueva Loja', 'Calle 10 de Agosto 420', 7);
INSERT INTO address (province, city, address, client_id) VALUES ('Napo', 'Tena', 'Av. 15 de Noviembre 508', 7);
INSERT INTO address (province, city, address, client_id) VALUES ('Morona Santiago', 'Macas', 'Av. Amazonas 604', 9);
INSERT INTO address (province, city, address, client_id) VALUES ('Zamora Chinchipe', 'Zamora', 'Calle La Paz 120', 8);
INSERT INTO address (province, city, address, client_id) VALUES ('Cotopaxi', 'Latacunga', 'Av. Unidad Nacional 312', 8);
INSERT INTO address (province, city, address, client_id) VALUES ('Bolívar', 'Guaranda', 'Calle Olmedo 221', 9);
INSERT INTO address (province, city, address, client_id) VALUES ('Cañar', 'Azogues', 'Av. Simón Bolívar 330', 9);